development:
  adapter: postgresql
  host: <%= ENV['DATABASE_HOST'] %>
  encoding: utf8
  database: <%= ENV['DATABASE_NAME'] %>
  pool: 5
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASS'] %>

